In [1]:
import fastf1
import pandas as pd
import os

In [2]:
if not os.path.exists('f1_cache'):
    os.makedirs('f1_cache')
fastf1.Cache.enable_cache('f1_cache')

In [3]:
def get_raw_race_results(year):
    print(f"--- Fetching Data for {year} ---")
    schedule = fastf1.get_event_schedule(year)
    
    all_race_data = []
    
    for index, event in schedule.iterrows():
        # Skip testing sessions, we only want real race weekends
        if event['EventFormat'] == 'testing':
            continue
            
        try:
            print(f"Loading {year} Round {event['RoundNumber']}: {event['EventName']}...")
            
            # Load only the Race session ('R'). 
            # We disable telemetry and weather to make the download very fast.
            session = fastf1.get_session(year, event['EventName'], 'R')
            session.load(telemetry=False, weather=False, messages=False)
            
            results = session.results
            
            # Loop through each driver's result in that race
            for _, driver in results.iterrows():
                all_race_data.append({
                    'Year': year,
                    'Round': event['RoundNumber'],
                    'Race_Name': event['EventName'],
                    'Driver_Code': driver['Abbreviation'],   # e.g., 'VER', 'NOR', 'HAM'
                    'Team': driver['TeamName'],              # e.g., 'Red Bull Racing'
                    'Finish_Position': driver['Position'],   # 1.0, 2.0, etc. (NaN if DNF)
                    'Points_Scored': driver['Points'],       # 25.0, 18.0, etc.
                    'Status': driver['Status']               # Tells you if it was an engine failure, crash, or finished
                })
        except Exception as e:
            # If a race hasn't happened yet (like late 2026 races), it will skip
            print(f"Skipping {event['EventName']} (Data not available yet)")
            
    return pd.DataFrame(all_race_data)

In [4]:
df_2025 = get_raw_race_results(2025)

--- Fetching Data for 2025 ---

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

Loading 2025 Round 1: Australian Grand Prix...

core        WARNING 	Fixed incorrect tyre stint information for driver '87'
core        WARNING 	Fixed incorrect tyre stint information for driver '30'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
core        WARNING 	Driver 4 completed the race distance 00:00.022000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '63', '12', '23', '18', '27', '16', '81', '44', '10', '22', '31', '87', '30', '5', '14', '55', '7', '6']
core           INFO 	Loading data for Chinese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

Loading 2025 Round 2: Chinese Grand Prix...

core           INFO 	Finished loading data for 20 drivers: ['81', '4', '63', '1', '31', '12', '23', '87', '18', '55', '6', '30', '7', '5', '27', '22', '14', '16', '44', '10']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 3: Japanese Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '12', '44', '6', '23', '87', '14', '22', '10', '55', '7', '27', '30', '31', '5', '18']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 4: Bahrain Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['81', '63', '4', '16', '44', '1', '10', '31', '22', '87', '12', '23', '6', '7', '14', '30', '18', '5', '55', '27']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 5: Saudi Arabian Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['81', '1', '16', '4', '63', '12', '44', '55', '23', '6', '14', '30', '87', '31', '27', '18', '7', '5', '22', '10']
core           INFO 	Loading data for Miami Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 6: Miami Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 81 completed the race distance 00:00.036000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '63', '1', '23', '12', '16', '44', '55', '22', '6', '31', '10', '27', '14', '18', '30', '5', '87', '7']
core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 7: Emilia Romagna Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '44', '23', '16', '63', '55', '6', '22', '14', '27', '10', '30', '18', '43', '87', '5', '12', '31']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 8: Monaco Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['4', '16', '81', '1', '44', '6', '31', '30', '23', '55', '63', '87', '43', '5', '18', '27', '22', '12', '14', '10']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 9: Spanish Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 19 drivers: ['81', '4', '16', '63', '27', '44', '6', '10', '14', '1', '30', '5', '22', '55', '43', '31', '87', '12', '23']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 10: Canadian Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['63', '1', '12', '81', '16', '44', '14', '27', '31', '55', '87', '22', '43', '5', '10', '6', '18', '4', '30', '23']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 11: Austrian Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 55)
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '16', '44', '63', '30', '14', '5', '27', '31', '87', '6', '10', '18', '43', '22', '23', '1', '12', '55']
core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 12: British Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 43)
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '27', '44', '1', '10', '18', '23', '14', '63', '87', '55', '31', '16', '22', '12', '6', '5', '30', '43']
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 13: Belgian Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '81'
core        WARNING 	Fixed incorrect tyre stint information for driver '4'
core        WARNING 	Fixed incorrect tyre stint information for driver '16'
core        WARNING 	Fixed incorrect tyre stint information for driver '1'
core        WARNING 	Fixed incorrect tyre stint information for driver '63'
core        WARNING 	Fixed incorrect tyre stint information for driver '23'
core        WARNING 	Fixed incorrect tyre stint information for driver '44'
core        WARNING 	Fixed incorrect tyre stint information for driver '30'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
core        WARNING 	Fixed incorrect tyre stint information for driver '10'
core        WARNING 	Fixed incorrect tyre stint information for driver '87'
core        WARNING 	Fixed incorrect tyre stint information for driver '27'
core        WARNING 	Fixed incorrect tyre stint information for driver '22'
core        WARNING 	Fixed incorrect tyre stint information for driver '18'
core        WARNING 	Fixed incorrect tyre stint information for driver '31'
core        WARNING 	Fixed incorrect tyre stint information for driver '12'
core        WARNING 	Fixed incorrect tyre stint information for driver '14'
core        WARNING 	Fixed incorrect tyre stint information for driver '55'
core        WARNING 	Fixed incorrect tyre stint information for driver '43'
core        WARNING 	Fixed incorrect tyre stint information for driver '6'
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '16', '1', '63', '23', '44', '30', '5', '10', '87', '27', '22', '18', '31', '12', '14', '55', '43', '6']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 14: Hungarian Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '63', '16', '14', '5', '18', '30', '1', '12', '6', '44', '27', '55', '23', '31', '22', '43', '10', '87']
core           INFO 	Loading data for Dutch Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 15: Dutch Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['81', '1', '6', '63', '23', '87', '18', '14', '22', '31', '43', '30', '55', '27', '5', '12', '10', '4', '16', '44']
core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 16: Italian Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 27)
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '44', '23', '5', '12', '6', '55', '87', '22', '30', '31', '10', '43', '18', '14', '27']
core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 17: Azerbaijan Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 1 completed the race distance 00:00.015000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['1', '63', '55', '12', '30', '22', '4', '44', '16', '6', '5', '87', '23', '31', '14', '27', '18', '10', '43', '81']
core           INFO 	Loading data for Singapore Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 18: Singapore Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['63', '1', '4', '81', '12', '16', '14', '44', '87', '55', '6', '22', '18', '23', '30', '43', '5', '31', '10', '27']
events      WARNING 	Correcting user input 'United States Grand Prix' to 'United States Grand Prix'
core           INFO 	Loading data for United States Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 19: United States Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '16', '44', '81', '63', '22', '27', '87', '14', '30', '18', '12', '23', '31', '6', '43', '5', '10', '55']
core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 20: Mexico City Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['4', '16', '1', '87', '81', '12', '63', '44', '31', '5', '22', '23', '6', '18', '10', '43', '55', '14', '27', '30']
core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 21: São Paulo Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 4 completed the race distance 00:00.010000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['4', '12', '1', '63', '81', '87', '30', '6', '27', '10', '23', '31', '55', '14', '43', '18', '22', '44', '16', '5']
core           INFO 	Loading data for Las Vegas Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 22: Las Vegas Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '63'
core           INFO 	Finished loading data for 20 drivers: ['1', '63', '12', '16', '55', '6', '27', '44', '31', '87', '14', '22', '10', '30', '43', '23', '5', '18', '4', '81']
events      WARNING 	Correcting user input 'Qatar Grand Prix' to 'Qatar Grand Prix'
core           INFO 	Loading data for Qatar Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 23: Qatar Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '81', '55', '4', '12', '63', '14', '16', '30', '22', '23', '44', '5', '43', '31', '10', '18', '6', '87', '27']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Loading 2025 Round 24: Abu Dhabi Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '81', '4', '16', '63', '14', '31', '44', '27', '18', '5', '87', '55', '22', '12', '23', '6', '30', '10', '43']

In [5]:
df_2025

,Year,Round,Race_Name,Driver_Code,Team,Finish_Position,Points_Scored,Status
0,2025,1,Australian Grand Prix,NOR,McLaren,1.0,25.0,Finished
1,2025,1,Australian Grand Prix,VER,Red Bull Racing,2.0,18.0,Finished
2,2025,1,Australian Grand Prix,RUS,Mercedes,3.0,15.0,Finished
3,2025,1,Australian Grand Prix,ANT,Mercedes,4.0,12.0,Finished
4,2025,1,Australian Grand Prix,ALB,Williams,5.0,10.0,Finished
...,...,...,...,...,...,...,...,...
474,2025,24,Abu Dhabi Grand Prix,ALB,Williams,16.0,0.0,Finished
475,2025,24,Abu Dhabi Grand Prix,HAD,Racing Bulls,17.0,0.0,Lapped
476,2025,24,Abu Dhabi Grand Prix,LAW,Racing Bulls,18.0,0.0,Lapped
477,2025,24,Abu Dhabi Grand Prix,GAS,Alpine,19.0,0.0,Lapped
478,2025,24,Abu Dhabi Grand Prix,COL,Alpine,20.0,0.0,Lapped

In [6]:
df_2026 = get_raw_race_results(2026)

--- Fetching Data for 2026 ---

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

Loading 2026 Round 1: Australian Grand Prix...

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 27)
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '16', '44', '1', '3', '87', '41', '5', '10', '31', '23', '30', '43', '55', '11', '18', '14', '77', '6', '81', '27']
core           INFO 	Loading data for Chinese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

Loading 2026 Round 2: Chinese Grand Prix...

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 1)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 5)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 23)
core        WARNING 	Driver 12 completed the race distance 00:00.022000 before the recorded end of the session.
core           INFO 	Finished loading data for 22 drivers: ['12', '63', '44', '16', '87', '10', '30', '6', '55', '43', '27', '41', '77', '31', '11', '3', '14', '18', '81', '1', '5', '23']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

Loading 2026 Round 3: Japanese Grand Prix...

core           INFO 	Finished loading data for 22 drivers: ['12', '81', '16', '63', '1', '44', '10', '3', '30', '31', '27', '6', '5', '41', '55', '43', '11', '14', '77', '23', '18', '87']
core           INFO 	Loading data for Miami Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

Loading 2026 Round 4: Miami Grand Prix...

core        WARNING 	Driver 12 completed the race distance 00:00.027000 before the recorded end of the session.
core           INFO 	Finished loading data for 22 drivers: ['12', '1', '81', '63', '3', '44', '43', '16', '55', '23', '87', '5', '31', '41', '14', '11', '18', '77', '27', '30', '10', '6']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

Loading 2026 Round 5: Canadian Grand Prix...

logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
core           INFO 	Finished loading data for 0 drivers: []
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

Loading 2026 Round 6: Monaco Grand Prix...

logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
core           INFO 	Finished loading data for 0 drivers: []
core           INFO 	Loading data for Barcelona Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

Loading 2026 Round 7: Barcelona Grand Prix...

logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
core           INFO 	Finished loading data for 0 drivers: []
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

Loading 2026 Round 8: Austrian Grand Prix...

logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
core           INFO 	Finished loading data for 0 drivers: []
core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

Loading 2026 Round 9: British Grand Prix...

logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
core           INFO 	Finished loading data for 0 drivers: []
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

Loading 2026 Round 10: Belgian Grand Prix...

logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
core           INFO 	Finished loading data for 0 drivers: []
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

Loading 2026 Round 11: Hungarian Grand Prix...

logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
core           INFO 	Finished loading data for 0 drivers: []
core           INFO 	Loading data for Dutch Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

Loading 2026 Round 12: Dutch Grand Prix...

logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
core           INFO 	Finished loading data for 0 drivers: []
core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

Loading 2026 Round 13: Italian Grand Prix...

logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
core           INFO 	Finished loading data for 0 drivers: []
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

Loading 2026 Round 14: Spanish Grand Prix...

logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
core           INFO 	Finished loading data for 0 drivers: []
core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

Loading 2026 Round 15: Azerbaijan Grand Prix...

logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
core           INFO 	Finished loading data for 0 drivers: []
core           INFO 	Loading data for Singapore Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

Loading 2026 Round 16: Singapore Grand Prix...

logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
core           INFO 	Finished loading data for 0 drivers: []
events      WARNING 	Correcting user input 'United States Grand Prix' to 'United States Grand Prix'
core           INFO 	Loading data for United States Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

Loading 2026 Round 17: United States Grand Prix...

logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
core           INFO 	Finished loading data for 0 drivers: []
core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

Loading 2026 Round 18: Mexico City Grand Prix...

logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
core           INFO 	Finished loading data for 0 drivers: []
core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

Loading 2026 Round 19: São Paulo Grand Prix...

logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
core           INFO 	Finished loading data for 0 drivers: []
core           INFO 	Loading data for Las Vegas Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

Loading 2026 Round 20: Las Vegas Grand Prix...

logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
core           INFO 	Finished loading data for 0 drivers: []
events      WARNING 	Correcting user input 'Qatar Grand Prix' to 'Qatar Grand Prix'
core           INFO 	Loading data for Qatar Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

Loading 2026 Round 21: Qatar Grand Prix...

logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
core           INFO 	Finished loading data for 0 drivers: []
core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

Loading 2026 Round 22: Abu Dhabi Grand Prix...

logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
core           INFO 	Finished loading data for 0 drivers: []

In [7]:
df_2026

,Year,Round,Race_Name,Driver_Code,Team,Finish_Position,Points_Scored,Status
0,2026,1,Australian Grand Prix,RUS,Mercedes,1.0,25.0,Finished
1,2026,1,Australian Grand Prix,ANT,Mercedes,2.0,18.0,Finished
2,2026,1,Australian Grand Prix,LEC,Ferrari,3.0,15.0,Finished
3,2026,1,Australian Grand Prix,HAM,Ferrari,4.0,12.0,Finished
4,2026,1,Australian Grand Prix,NOR,McLaren,5.0,10.0,Finished
...,...,...,...,...,...,...,...,...
83,2026,4,Miami Grand Prix,BOT,Cadillac,18.0,0.0,Lapped
84,2026,4,Miami Grand Prix,HUL,Audi,19.0,0.0,Retired
85,2026,4,Miami Grand Prix,LAW,Racing Bulls,20.0,0.0,Retired
86,2026,4,Miami Grand Prix,GAS,Alpine,21.0,0.0,Retired
87,2026,4,Miami Grand Prix,HAD,Red Bull Racing,22.0,0.0,Retired

In [8]:
df_2025["Driver_Code"].unique()

array(['NOR', 'VER', 'RUS', 'ANT', 'ALB', 'STR', 'HUL', 'LEC', 'PIA',
       'HAM', 'GAS', 'TSU', 'OCO', 'BEA', 'LAW', 'BOR', 'ALO', 'SAI',
       'DOO', 'HAD', 'COL'], dtype=object)

In [9]:
df_2025["Finish_Position"].unique()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [10]:
df_2025["Status"].unique()

array(['Finished', 'Retired', 'Lapped', 'Disqualified', 'Did not start'],
      dtype=object)

In [11]:
df_2025["Finished"] = df_2025["Status"].isin(["Finished","Lapped"]).astype(int)

In [12]:
df_2025

,Year,Round,Race_Name,Driver_Code,Team,Finish_Position,Points_Scored,Status,Finished
0,2025,1,Australian Grand Prix,NOR,McLaren,1.0,25.0,Finished,1
1,2025,1,Australian Grand Prix,VER,Red Bull Racing,2.0,18.0,Finished,1
2,2025,1,Australian Grand Prix,RUS,Mercedes,3.0,15.0,Finished,1
3,2025,1,Australian Grand Prix,ANT,Mercedes,4.0,12.0,Finished,1
4,2025,1,Australian Grand Prix,ALB,Williams,5.0,10.0,Finished,1
...,...,...,...,...,...,...,...,...,...
474,2025,24,Abu Dhabi Grand Prix,ALB,Williams,16.0,0.0,Finished,1
475,2025,24,Abu Dhabi Grand Prix,HAD,Racing Bulls,17.0,0.0,Lapped,1
476,2025,24,Abu Dhabi Grand Prix,LAW,Racing Bulls,18.0,0.0,Lapped,1
477,2025,24,Abu Dhabi Grand Prix,GAS,Alpine,19.0,0.0,Lapped,1
478,2025,24,Abu Dhabi Grand Prix,COL,Alpine,20.0,0.0,Lapped,1

In [13]:
df_2026["Finished"] = df_2026["Status"].isin(["Finished","Lapped"]).astype(int)

In [14]:
driver_team = df_2025.groupby("Driver_Code")["Team"].first().to_dict()

In [15]:
driver_team

{'ALB': 'Williams',
 'ALO': 'Aston Martin',
 'ANT': 'Mercedes',
 'BEA': 'Haas F1 Team',
 'BOR': 'Kick Sauber',
 'COL': 'Alpine',
 'DOO': 'Alpine',
 'GAS': 'Alpine',
 'HAD': 'Racing Bulls',
 'HAM': 'Ferrari',
 'HUL': 'Kick Sauber',
 'LAW': 'Red Bull Racing',
 'LEC': 'Ferrari',
 'NOR': 'McLaren',
 'OCO': 'Haas F1 Team',
 'PIA': 'McLaren',
 'RUS': 'Mercedes',
 'SAI': 'Williams',
 'STR': 'Aston Martin',
 'TSU': 'Racing Bulls',
 'VER': 'Red Bull Racing'}

In [16]:
df_ppf = df_2025.loc[df_2025["Finished"]==1].groupby("Driver_Code")["Points_Scored"].mean().reset_index().sort_values(ascending=False,by=["Points_Scored"])

In [17]:
df_ppf

   Driver_Code  Points_Scored
13         NOR      18.761905
15         PIA      17.318182
20         VER      16.913043
16         RUS      12.041667
12         LEC      10.714286
2          ANT       6.750000
9          HAM       6.428571
0          ALB       3.500000
17         SAI       2.842105
1          ALO       2.684211
10         HUL       2.550000
8          HAD       2.380952
11         LAW       2.000000
3          BEA       1.857143
14         OCO       1.478261
18         STR       1.380952
4          BOR       1.000000
7          GAS       0.952381
19         TSU       0.913043
6          DOO       0.000000
5          COL       0.000000

In [18]:
df_team = df_2025.groupby("Team")["Points_Scored"].sum().reset_index().sort_values(by="Points_Scored",ascending=False)

In [19]:
df_team

              Team  Points_Scored
5          McLaren          775.0
6         Mercedes          424.0
8  Red Bull Racing          410.0
2          Ferrari          360.0
9         Williams          124.0
7     Racing Bulls           88.0
1     Aston Martin           80.0
3     Haas F1 Team           73.0
4      Kick Sauber           70.0
0           Alpine           20.0

In [20]:
team_points = df_team.set_index("Team").to_dict()["Points_Scored"]
team_points

{'McLaren': 775.0,
 'Mercedes': 424.0,
 'Red Bull Racing': 410.0,
 'Ferrari': 360.0,
 'Williams': 124.0,
 'Racing Bulls': 88.0,
 'Aston Martin': 80.0,
 'Haas F1 Team': 73.0,
 'Kick Sauber': 70.0,
 'Alpine': 20.0}

In [21]:
df_reliability = df_2026.groupby("Driver_Code")["Finished"].mean().reset_index().sort_values(by="Finished")

In [22]:
df_reliability

   Driver_Code  Finished
1          ALO      0.50
8          HAD      0.50
10         HUL      0.50
17         PIA      0.50
20         STR      0.50
5          BOT      0.75
7          GAS      0.75
0          ALB      0.75
11         LAW      0.75
14         NOR      0.75
3          BEA      0.75
4          BOR      0.75
21         VER      0.75
9          HAM      1.00
6          COL      1.00
2          ANT      1.00
15         OCO      1.00
13         LIN      1.00
12         LEC      1.00
16         PER      1.00
19         SAI      1.00
18         RUS      1.00

In [23]:
df_agg_2025 = df_ppf.copy()
df_agg_2025["Team_Point"]= df_agg_2025["Driver_Code"].map(driver_team).map(team_points)
df_agg_2025

   Driver_Code  Points_Scored  Team_Point
13         NOR      18.761905       775.0
15         PIA      17.318182       775.0
20         VER      16.913043       410.0
16         RUS      12.041667       424.0
12         LEC      10.714286       360.0
2          ANT       6.750000       424.0
9          HAM       6.428571       360.0
0          ALB       3.500000       124.0
17         SAI       2.842105       124.0
1          ALO       2.684211        80.0
10         HUL       2.550000        70.0
8          HAD       2.380952        88.0
11         LAW       2.000000       410.0
3          BEA       1.857143        73.0
14         OCO       1.478261        73.0
18         STR       1.380952        80.0
4          BOR       1.000000        70.0
7          GAS       0.952381        20.0
19         TSU       0.913043        88.0
6          DOO       0.000000        20.0
5          COL       0.000000        20.0

In [24]:
df_agg_2025 = pd.merge(df_agg_2025, df_reliability, on="Driver_Code", how="inner")

In [25]:
df_agg_2025

   Driver_Code  Points_Scored  Team_Point  Finished
0          NOR      18.761905       775.0      0.75
1          PIA      17.318182       775.0      0.50
2          VER      16.913043       410.0      0.75
3          RUS      12.041667       424.0      1.00
4          LEC      10.714286       360.0      1.00
5          ANT       6.750000       424.0      1.00
6          HAM       6.428571       360.0      1.00
7          ALB       3.500000       124.0      0.75
8          SAI       2.842105       124.0      1.00
9          ALO       2.684211        80.0      0.50
10         HUL       2.550000        70.0      0.50
11         HAD       2.380952        88.0      0.50
12         LAW       2.000000       410.0      0.75
13         BEA       1.857143        73.0      0.75
14         OCO       1.478261        73.0      1.00
15         STR       1.380952        80.0      0.50
16         BOR       1.000000        70.0      0.75
17         GAS       0.952381        20.0      0.75
18         COL       0.000000        20.0      1.00

In [26]:
import numpy as np

# Copy your aggregated 20-row dataframe into the new binning dataframe
# Change 'your_merged_df' to the actual name of the dataframe from your screenshot
df_bin_2025 = df_agg_2025.copy()

# 1. Calculate the Z-Scores for all three columns
cols_to_zscore = ["Points_Scored", "Team_Point", "Finished"]

for col in cols_to_zscore:
    mean_val = df_bin_2025[col].mean()
    std_val = df_bin_2025[col].std()
    df_bin_2025[f"{col}_Z"] = (df_bin_2025[col] - mean_val) / std_val

# 2. Discretize Driver Skill
conditions_driver = [
    (df_bin_2025["Points_Scored_Z"] > 1.5),
    (df_bin_2025["Points_Scored_Z"] > 0.5),
    (df_bin_2025["Points_Scored_Z"] > -0.5)
]
choices_driver = ["Elite", "Good", "Mid"]
df_bin_2025["Driver_Skill_25"] = np.select(conditions_driver, choices_driver, default="Low")

# 3. Discretize Team Legacy
conditions_team = [
    (df_bin_2025["Team_Point_Z"] > 1.0),
    (df_bin_2025["Team_Point_Z"] > -0.5)
]
choices_team = ["Top_Tier", "Midfield"]
df_bin_2025["Team_Legacy_25"] = np.select(conditions_team, choices_team, default="Backmarker")

# 4. Discretize Reliability
conditions_rel = [
    (df_bin_2025["Finished_Z"] > -1.0) 
]
choices_rel = ["Solid"]
df_bin_2025["Reliability_26"] = np.select(conditions_rel, choices_rel, default="Fragile")

# View the final dataset for Netica
display_cols = ["Driver_Code", "Driver_Skill_25", "Team_Legacy_25", "Reliability_26"]

In [27]:
df_parent = df_bin_2025[display_cols]

In [28]:
df_parent

   Driver_Code Driver_Skill_25 Team_Legacy_25 Reliability_26
0          NOR           Elite       Top_Tier          Solid
1          PIA           Elite       Top_Tier        Fragile
2          VER           Elite       Midfield          Solid
3          RUS            Good       Midfield          Solid
4          LEC            Good       Midfield          Solid
5          ANT             Mid       Midfield          Solid
6          HAM             Mid       Midfield          Solid
7          ALB             Mid     Backmarker          Solid
8          SAI             Mid     Backmarker          Solid
9          ALO             Low     Backmarker        Fragile
10         HUL             Low     Backmarker        Fragile
11         HAD             Low     Backmarker        Fragile
12         LAW             Low       Midfield          Solid
13         BEA             Low     Backmarker          Solid
14         OCO             Low     Backmarker          Solid
15         STR             Low     Backmarker        Fragile
16         BOR             Low     Backmarker          Solid
17         GAS             Low     Backmarker          Solid
18         COL             Low     Backmarker          Solid

In [29]:
df_pace = df_2026.dropna(subset=['Finish_Position']) 
df_pace_avg = df_pace.groupby('Driver_Code')['Finish_Position'].mean().reset_index()

# 2. Discretize into Netica States
conditions_pace = [
    (df_pace_avg['Finish_Position'] <= 3.5),
    (df_pace_avg['Finish_Position'] <= 10.5)
]
choices_pace = ['P1_P3', 'P4_P10']
df_pace_avg['Expected_Race_Pace_26'] = np.select(conditions_pace, choices_pace, default='Out_of_Points')

# 3. Merge this new column into your existing df_parent
df_final = pd.merge(df_parent, df_pace_avg[['Driver_Code', 'Expected_Race_Pace_26']], on='Driver_Code', how='left')

# 4. Handle drivers who might not have finished a race in 2026 yet
df_final['Expected_Race_Pace_26'] = df_final['Expected_Race_Pace_26'].fillna('Out_of_Points')

# View the final result

In [30]:
df_final

,Driver_Code,Driver_Skill_25,Team_Legacy_25,Reliability_26,Expected_Race_Pace_26
0,NOR,Elite,Top_Tier,Solid,P4_P10
1,PIA,Elite,Top_Tier,Fragile,Out_of_Points
2,VER,Elite,Midfield,Solid,P4_P10
3,RUS,Good,Midfield,Solid,P1_P3
4,LEC,Good,Midfield,Solid,P4_P10
5,ANT,Mid,Midfield,Solid,P1_P3
6,HAM,Mid,Midfield,Solid,P4_P10
7,ALB,Mid,Backmarker,Solid,Out_of_Points
8,SAI,Mid,Backmarker,Solid,Out_of_Points
9,ALO,Low,Backmarker,Fragile,Out_of_Points
10,HUL,Low,Backmarker,Fragile,Out_of_Points
11,HAD,Low,Backmarker,Fragile,Out_of_Points
12,LAW,Low,Midfield,Solid,Out_of_Points
13,BEA,Low,Backmarker,Solid,Out_of_Points
14,OCO,Low,Backmarker,Solid,Out_of_Points
15,STR,Low,Backmarker,Fragile,Out_of_Points
16,BOR,Low,Backmarker,Solid,Out_of_Points
17,GAS,Low,Backmarker,Solid,Out_of_Points
18,COL,Low,Backmarker,Solid,Out_of_Points

In [37]:
df_final.to_csv("final.csv")

In [36]:
# 1. Define the columns you want to calculate the distribution for
node_columns = [
    'Driver_Skill_25', 
    'Team_Legacy_25', 
    'Reliability_26', 
    'Expected_Race_Pace_26'
]

# 2. Calculate the probability distribution for each column
dist_dict = {col: df_final[col].value_counts(normalize=True) for col in node_columns}

# 3. Concatenate the dictionary into a MultiIndex Series
multi_index_series = pd.concat(dist_dict)

# 4. Name the indexes for clean formatting
multi_index_series.index.names = ['Variable_Name', 'State']

# 5. Convert it into a DataFrame for better display (THE FIX IS HERE)
df_distributions = multi_index_series.to_frame(name='Probability')

# Explicitly display the table
display(df_distributions)

                                     Probability
Variable_Name         State
Driver_Skill_25       Low               0.526316
                      Mid               0.210526
                      Elite             0.157895
                      Good              0.105263
Team_Legacy_25        Backmarker        0.578947
                      Midfield          0.315789
                      Top_Tier          0.105263
Reliability_26        Solid             0.736842
                      Fragile           0.263158
Expected_Race_Pace_26 Out_of_Points     0.684211
                      P4_P10            0.210526
                      P1_P3             0.105263

In [38]:
df_distributions.to_csv("dists.csv")